language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

env:
  - STABILITY=''
  - STABILITY='--prefer-lowest'

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
    - composer self-update
    - composer update $STABILITY

script: vendor/bin/phpunit --coverage-clover clover

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover clover

