language: php

matrix:
  allow_failures:
    - hhvm

php:
  - 5.3
  - 5.4
  - hhvm

before_script:
    - composer self-update
    - composer install --dev

script: phpunit --coverage-clover clover

after_success:
    - curl -sL https://bit.ly/artifact-uploader | php

