language: php

sudo: false

git:
    depth: 1

cache:
  directories:
    - $HOME/.composer/cache

matrix:
    include:
        - php: 7.1
        - php: 7.1
          env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
    fast_finish: true

before_script:
    - if [[ "$COMPOSER_FLAGS"  = "" ]]; then PHPUNIT_FLAGS="--coverage-clover clover"; else PHPUNIT_FLAGS=""; fi
    - composer update $COMPOSER_FLAGS

script:
    - vendor/bin/phpunit $PHPUNIT_FLAGS
    - php tests/benchmark.php json 10
#    - php tests/benchmark.php yml 10
    - php tests/benchmark.php xml 10

after_success:
    - if [[ "$COMPOSER_FLAGS"  = "" ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [[ "$COMPOSER_FLAGS"  = "" ]]; then php ocular.phar code-coverage:upload --format=php-clover clover; fi

